### ISSUE TITLE
When performing a specmatch, an error is triggered because of scipy module

### ISSUE THREAD

**Issue by ycollet** [brummer10/SpecMatch#5]
I recorded 2 sounds and load these sounds in specmatch.
When I click on "Generate", an error is printed in the console:
```
specmatch
Traceback (most recent call last):
  File "/home/collette/python/specmatch/lib64/python3.13/site-packages/specmatch/ui.py", line 75, in __call__
    self.set_file(self.nr, self.w.get_filename())
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/collette/python/specmatch/lib64/python3.13/site-packages/specmatch/ui.py", line 385, in set_file
    write_sndfile(self.calc.ir, name, self.get_sample_rate(), "pcm24")
                  ^^^^^^^^^^^^
  File "/home/collette/python/specmatch/lib64/python3.13/site-packages/specmatch/spectrum.py", line 436, in ir
    self.ir = self.ir_smoother.get_ir(self.sz, self._magnitude)
              ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/collette/python/specmatch/lib64/python3.13/site-packages/specmatch/spectrum.py", line 219, in get_ir
    w = sig.hamming(2*wd)[-wd:]
        ^^^^^^^^^^^
AttributeError: module 'scipy.signal' has no attribute 'hamming'

```

**Comment by ycollet** [comment]
The list of modules installed in the virtual env:
```
pip freeze
audioop-lts==0.2.1
cffi==1.17.1
contourpy==1.3.2
cycler==0.12.1
fonttools==4.57.0
kiwisolver==1.4.8
llvmlite==0.44.0
matplotlib==3.10.1
numba==0.61.2
numpy==2.2.5
packaging==25.0
pillow==11.2.1
pycairo==1.28.0
pycparser==2.22
pydub==0.25.1
PyGObject==3.52.3
pyparsing==3.2.3
python-dateutil==2.9.0.post0
resampy==0.4.3
scipy==1.15.2
six==1.17.0
soundfile==0.13.1
specmatch==0.10.0
```

**Comment by ycollet** [comment]
I just replaced sig.hamming by sig.windows.hamming in specmatch/spectrum.py and it worked

**Comment by brummer10** [comment]
Yep, that works. 
Nice catch.

**Comment by Mirochill** [comment]
This looks fixed on current main: specmatch/spectrum.py now uses sig.windows.hamming(2*wd)[-wd:], introduced in commit 1f9f819 (Fix issue #5). I don't see a PR needed here; the issue may just need closing or release follow-up.
